### ISSUE TITLE
Select Navigation2 branch

### ISSUE THREAD

**Issue by chcorbato** [MROS-RobMoSys-ITP/navigation2#1]
Yes. The real question is if we work in master (of navigation) or a stable version. 

If we were working in ROS1, I would instead prefer a stable version, but in ROS2, right now, the benefits are more significant in master, I think. So, the release of ROS2 would be the minimum to compile master of navigation2.

F.

El vie., 1 nov. 2019 18:51, Ricardo Sanz <Ricardo.Sanz@upm.es> escribió:
Hi,

Note that support for Eloquent will end on November 2020 but support for Dashing will end on May 2021.

R.
 

On Thu, Oct 31, 2019 at 9:12 PM Lange Ralph (CR/AEE1) <Ralph.Lange@de.bosch.com> wrote:
Yes, packages are already available – but beta only. Release will be on 22nd November.

 

Mit freundlichen Grüßen / Best regards 

Ralph Lange
CR/AEE1

Tel. +49 711 811-27147 | Mobil +49 1525 8813413 

From: Francisco Martín Rico <francisco.rico@urjc.es> 
Sent: Donnerstag, 31. Oktober 2019 20:42
To: Lange Ralph (CR/AEE1) <Ralph.Lange@de.bosch.com>
Cc: G.A. vd. Hoorn - 3ME <g.a.vanderhoorn@tudelft.nl>; Carlos Hernandez Corbato - 3ME <C.H.Corbato@tudelft.nl>; Nordmann Arne (CR/AEX3) <Arne.Nordmann@de.bosch.com>; Ricardo Sanz <Ricardo.Sanz@upm.es>; Andrzej Wasowski <wasowski@itu.dk>
Subject: Re: MROS - ROS2 Navigation version

 

Dear colleagues,

 

We could also work on master, and install ros2 eloquent from packages. I have just checked it out. 

 

Best regards

 

El jue., 31 oct. 2019 a las 20:11, Francisco Martín Rico (<francisco.rico@urjc.es>) escribió:

Dear all,

 

First of all, RobMoSys Discourse is working fine for me.

 

Regarding the navigation2 repo, I am using https://github.com/ros-planning/navigation2.git, but we should decide what branch we will be working on.

- dashing-devel : It should compile with the last version available packaged version (dashing), but right now it is not compiling because some version problems that Davide commented me last week.

- master : We need to compile from sources the last version of ros2 (eloquent) because there are significant changes in the API of some dependencies (tf2_ros at least) not compatible with dashing.

 

Working in dashing-devel let us work in more stable version but in the current state of navigation2, its functionality could be very reduced. Working in master lets us benefit from more functionality, but sometimes something could be broken. Besides, if we work in master, it is convenient if we want to contribute with our development to navigation2.

 

IMHO, I would like to work in master. Call me crazy ;P , but it is not a strong position. If you consider the other option, it's fine.

 

I attach a ros2.repos file with ros2 eloquent master, and with the repos of navigation2 (master) and turtlebot3.

 

Best, 

Francisco

 

 

El jue., 31 oct. 2019 a las 19:40, Lange Ralph (CR/AEE1) (<Ralph.Lange@de.bosch.com>) escribió:

Hello Carlos,

we're also using https://github.com/ros-planning/navigation2.
ROS Discourse or mailing list are both fine for me.

Best regards

Ralph

Mit freundlichen Grüßen / Best regards 

Dr. Ralph Lange

SW Systems Engineering (CR/AEE1) 
Robert Bosch GmbH | Renningen | 70465 Stuttgart | GERMANY | www.bosch.com 
Tel. +49 711 811-27147 | Mobil +49 1525 8813413 | Ralph.Lange@de.bosch.com 

Sitz: Stuttgart, Registergericht: Amtsgericht Stuttgart, HRB 14000;
Aufsichtsratsvorsitzender: Franz Fehrenbach; Geschäftsführung: Dr. Volkmar Denner,
Prof. Dr. Stefan Asenkerschbaumer, Dr. Michael Bolle, Dr. Christian Fischer, Dr. Stefan Hartung,
Dr. Markus Heyn, Dr. Dirk Hoheisel, Christoph Kübel, Rolf Najork, Uwe Raschke, Peter Tyroller

-----Original Message-----
From: G.A. vd. Hoorn - 3ME <g.a.vanderhoorn@tudelft.nl> 
Sent: Donnerstag, 31. Oktober 2019 14:44
To: Carlos Hernandez Corbato - 3ME <C.H.Corbato@tudelft.nl>; Francisco Martín Rico <francisco.rico@urjc.es>; Lange Ralph (CR/AEE1) <Ralph.Lange@de.bosch.com>; Nordmann Arne (CR/AEX3) <Arne.Nordmann@de.bosch.com>
Cc: Ricardo Sanz <Ricardo.Sanz@upm.es>; Andrzej Wasowski <wasowski@itu.dk>
Subject: Re: MROS - ROS2 Navigation version

On 10/31/19 11:45 AM, Carlos Hernandez Corbato - 3ME wrote:
> Hi Gijs, Francisco, Ralph and Arne,
> 
> Could you please let us know which repository for ROS2 Navigation are 
> you using (if any), and which one do you think we should use in MROS?

See [1] for the main navigation2 repository.

> PS is anyone getting the messages from RobMoSys Discourse? I can setup 
> a mailing list if we prefer that for project communication

I haven't yet registered.

Mailinglist would be ok for me as well, as we would have total control and it would be more private (I imagine).

Gijs

[1] https://github.com/ros-planning/navigation2

**Comment by fmrico** [comment]
Hi all,

We are currently working in master and ROS2 eloquent.

If you consider any different option, we could discuss it in this issue ;)

Best

**Comment by chcorbato** [comment]
Info added to the [wiki of this repo](https://github.com/MROS-RobMoSys-ITP/navigation2/wiki)
