### ISSUE TITLE
Problem with navigation2 and bringup example with turtlebot3 gazebo sim 

### ISSUE THREAD

**Issue by chcorbato** [MROS-RobMoSys-ITP/navigation2#7]
I'm trying to get navigation2 running, and I'm almost there but I do not see anything in RVIz when trying the bringup [example](https://github.com/MROS-RobMoSys-ITP/navigation2/tree/master/nav2_bringup/bringup) with turtlebot3
- No messages on Topic map are received
I think the problem can be related to this WARNING in the terminal where I launched navigation2
```
[planner_server-5] Warning: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[planner_server-5]          at line 133 in /home/chcorbato/ros2_eloquent/src/ros2/geometry2/tf2/src/buffer_core.cpp
```

- I have followed the instructions to install `ros2` and `navigation2` from sources
  - from the previous instructions I have also installed `tutlebot3` from sources

Any help is welcome!

Also, if any of you have a running setup of navigation 2 with gazebo, please feel free to share.

Carlos

**Comment by fmrico** [comment]
Hi Carlos,

Yes, it is a little bit confusing at initial ;)

1. Launch navigation. I use` ros2 launch nav2_bringup nav2_tb3_simulation_launch.py`
2. In RViz, push startup button
3. Set initial pose of the robot using the "2D Pose Estimate" in the toolbar

Good luck!!

**Comment by chcorbato** [comment]
Thanks @fmrico !
Getting there, now debugging why my turtlebot is a waffle too thin  :-D
![Screenshot from 2019-12-06 09-26-08](https://user-images.githubusercontent.com/9592617/70308229-125ccd00-180b-11ea-9e7a-5db37c863f00.png)

**Comment by fmrico** [comment]
Hi!!

Did you [download](https://github.com/ROBOTIS-GIT/turtlebot3_simulations/tree/ros2/turtlebot3_gazebo/models) and set up the models?

export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:<full/path/to/my_robot/models>
gazebo --verbose -s libgazebo_ros_init.so <full/path/to/my_gazebo.world>

Best!!!

**Comment by chcorbato** [comment]
Thanks, I was using this path for the models:
`export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:~/turtlebot3_ws/install/turtlebot3_gazebo/share/turtlebot3_gazebo/models`
now using:
`export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/home/chcorbato/turtlebot3_ws/src/turtlebot3/turtlebot3_simulations/turtlebot3_gazebo/models`
the turtlebot3 shows up correctly in gazebo

I'm still fighting issues setting up navigation, @fmrico @jginesclavero @lbajo do you have some written instructions to try navigation2? maybe with a Thiago simulation?

**Comment by fmrico** [comment]
Right now, ii's adding more documentation to navigation2. They have added this [getting started](https://ros-planning.github.io/navigation2/getting_started/index.html). 

Give us more details about your issues, please. We are not running navigation2 with Tiago simulator. We could try it next week.
